version: '3.4'

services:
  b2b:
    image: b2b
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - media_volume:/app/media
      - log_volume:/app/logs
    env_file:
      - .env
    depends_on:
      - pgbouncer
    command: >
      sh -c "python manage.py migrate &&
            python manage.py compilemessages &&
            python manage.py runserver 0.0.0.0:8000"
  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    environment:
      - POSTGRESQL_HOST=postgresdb
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - PGBOUNCER_DATABASE=${POSTGRES_DB}
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MAX_CLIENT_CONN=1000
      - PGBOUNCER_DEFAULT_POOL_SIZE=25
      - PGBOUNCER_RESERVE_POOL_SIZE=5
      - PGBOUNCER_SERVER_ROUND_ROBIN=1
      - PGBOUNCER_AUTH_TYPE=trust
    ports:
      - "6432:6432"
    # don't expose db port for production
    env_file:
      - .env
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:17.5
    volumes:
      - pgdata:/var/lib/postgresql/data
    # don't expose db port for production
    ports:
      - 5432:5432
    env_file:
      - .env
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=512MB
    # shared_buffers > 1GB for production (default is 128MB)
    # max_connections should be lower when using PgBouncer
  locust:
    image: locustio/locust:2.37.13
    ports:
      - "8089:8089"  # Locust web UI
    volumes:
      - ./locust:/mnt/locust
    working_dir: /mnt/locust
    command: >
      -f locustfile.py --host=http://b2b:8000
    depends_on:
      - b2b

volumes:
  pgdata:
  media_volume:
  log_volume: