# Generated by Django 5.2 on 2025-07-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='تومان', max_digits=12, verbose_name='مبلغ درخواستی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('complete', 'تکمیل شده'), ('reject', 'رد شده')], default='pending', max_length=8, verbose_name='وضعیت درخواست')),
                ('is_processed', models.BooleanField(default=False, verbose_name='وضعیت پردازش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست اعتبار',
                'verbose_name_plural': 'درخواست های اعتبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='تومان', max_digits=12, verbose_name='مبلغ')),
                ('type', models.CharField(choices=[('balance_top_up', 'افزایش موجودی حساب'), ('simcard_charge', 'شارژ سیم کارت')], max_length=15, verbose_name='نوع تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
