# Generated by Django 5.2 on 2025-07-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='toman', max_digits=12, verbose_name='requested amount')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('complete', 'تکمیل شده'), ('reject', 'رد شده')], default='pending', max_length=8, verbose_name='request status')),
                ('is_processed', models.BooleanField(default=False, verbose_name='process status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'credit request',
                'verbose_name_plural': 'credit requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='toman', max_digits=12, verbose_name='amount')),
                ('type', models.CharField(choices=[('balance_top_up', 'افزایش موجودی حساب'), ('simcard_charge', 'شارژ سیم کارت')], max_length=15, verbose_name='transaction type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
