# Generated by Django 5.2 on 2025-07-14 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_request',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_request_transaction', to='finance.creditrequest', verbose_name='درخواست اعتبار'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر فروشنده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='simcard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcard_transactions', to='inventory.simcard', verbose_name='شماره سیم کارت'),
        ),
        migrations.AddIndex(
            model_name='creditrequest',
            index=models.Index(fields=['-created_at'], name='finance_cre_created_759d17_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='finance_tra_type_390c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='finance_tra_created_945fa1_idx'),
        ),
    ]
