# Generated by Django 5.2 on 2025-07-15 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('inventory', '0002_alter_simcard_options_alter_simcard_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'credit request', 'verbose_name_plural': 'credit requests'},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='toman', max_digits=12, verbose_name='requested amount'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='process status'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('complete', 'تکمیل شده'), ('reject', 'رد شده')], default='pending', max_length=8, verbose_name='request status'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='toman', max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='credit_request',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_request_transaction_history', to='finance.creditrequest', verbose_name='credit request'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions_history', to=settings.AUTH_USER_MODEL, verbose_name='seller user'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='simcard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcard_transactions_history', to='inventory.simcard', verbose_name='simcard number'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='type',
            field=models.CharField(choices=[('balance_top_up', 'افزایش موجودی حساب'), ('simcard_charge', 'شارژ سیم کارت')], max_length=15, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
    ]
