# Generated by Django 5.2 on 2025-07-16 14:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='toman', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='requested amount'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='toman', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount'),
        ),
    ]
