# Generated by Django 5.2 on 2025-07-15 16:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='تومان', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='balance'),
        ),
    ]
