# Generated by Django 5.2 on 2025-07-15 17:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='toman', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='balance'),
        ),
    ]
