# Generated by Django 5.2 on 2025-07-15 20:15

import utils.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, unique=True, validators=[utils.validators.validate_sim_number], verbose_name='mobile number')),
                ('operator', models.CharField(choices=[('mtn', 'ایرانسل'), ('mci', 'همراه اول')], max_length=3, verbose_name='mobile number operator')),
                ('balance', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='toman', max_digits=12, verbose_name='simcard charge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'sim card',
                'verbose_name_plural': 'sim cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_s_created_7ea6f7_idx')],
            },
        ),
    ]
