# Generated by Django 5.2 on 2025-07-14 11:13

import inventory.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, unique=True, validators=[inventory.models.validate_sim_number], verbose_name='شماره موبایل')),
                ('operator', models.CharField(choices=[('mtn', 'ایرانسل'), ('mci', 'همراه اول')], max_length=3, verbose_name='اپراتور شماره موبایل')),
                ('balance', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='تومان', max_digits=12, verbose_name='شارژ سیمکارت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سیم کارت',
                'verbose_name_plural': 'سیم کارت ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_s_created_7ea6f7_idx')],
            },
        ),
    ]
