# Generated by Django 5.2 on 2025-07-15 17:42

import inventory.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'sim card', 'verbose_name_plural': 'sim cards'},
        ),
        migrations.AlterField(
            model_name='simcard',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='toman', max_digits=12, verbose_name='simcard charge'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='number',
            field=models.CharField(max_length=11, unique=True, validators=[inventory.validators.validate_sim_number], verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='operator',
            field=models.CharField(choices=[('mtn', 'ایرانسل'), ('mci', 'همراه اول')], max_length=3, verbose_name='mobile number operator'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
    ]
